# Twitter Thread Chunker - Secrets Configuration Template
# 
# This file should be placed in the .streamlit folder as 'secrets.toml'
# For local development: .streamlit/secrets.toml
# For Streamlit Cloud: Add these as secrets in the app dashboard
#
# To get these credentials:
# 1. Go to https://developer.twitter.com/en/portal/dashboard
# 2. Create a new app or use existing one
# 3. Generate API keys with Read and Write permissions
# 4. Copy the values below

[twitter]
consumer_key = "your_consumer_key_here"
consumer_secret = "your_consumer_secret_here"
access_token = "your_access_token_here"
access_token_secret = "your_access_token_secret_here"

# Example (replace with your actual credentials):
# [twitter]
# consumer_key = "AbCdEfGhIjKlMnOpQrSt"
# consumer_secret = "1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL"
# access_token = "1234567890-AbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl"
# access_token_secret = "AbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQr"
